/**
 * Seed exercise names used for preference suggestions and the Phase 1 synthetic
 * demo workout. Phase 2 replaces this with the structured exercise catalog;
 * the names are kept stable so stored preferences resolve by alias later.
 */
export const SEED_EXERCISE_NAMES: readonly string[] = [
  'Barbell Bench Press',
  'Incline Barbell Bench Press',
  'Dumbbell Bench Press',
  'Incline Dumbbell Press',
  'Machine Chest Press',
  'Push-Up',
  'Cable Fly',
  'Pec Deck',
  'Dip',
  'Overhead Press',
  'Dumbbell Shoulder Press',
  'Lateral Raise',
  'Cable Lateral Raise',
  'Rear Delt Fly',
  'Face Pull',
  'Pull-Up',
  'Chin-Up',
  'Lat Pulldown',
  'Barbell Row',
  'Dumbbell Row',
  'Seated Cable Row',
  'Chest-Supported Row',
  'Deadlift',
  'Romanian Deadlift',
  'Trap Bar Deadlift',
  'Back Squat',
  'Front Squat',
  'Goblet Squat',
  'Hack Squat',
  'Leg Press',
  'Bulgarian Split Squat',
  'Walking Lunge',
  'Leg Extension',
  'Leg Curl',
  'Hip Thrust',
  'Standing Calf Raise',
  'Barbell Curl',
  'EZ-Bar Curl',
  'Dumbbell Curl',
  'Incline Dumbbell Curl',
  'Hammer Curl',
  'Preacher Curl',
  'Cable Curl',
  'Band Curl',
  'Close-Grip Bench Press',
  'Skull Crusher',
  'Overhead Triceps Extension',
  'Cable Triceps Pushdown',
  'Band Triceps Pushdown',
  'Plank',
  'Hanging Leg Raise',
  'Ab Wheel Rollout',
];
